schema = 3

[mod]
  [mod."github.com/c-bata/go-prompt"]
    version = "v0.2.6"
    hash = "sha256-C78Tk6uxPMyL2ftda8Z4Av801AaVKgVhEV/T2eRlFVY="
  [mod."github.com/cavaliercoder/grab"]
    version = "v2.0.0+incompatible"
    hash = "sha256-MumGqHqp5bjWpMuULRdo9snsEMk5p4eRl50mmoFelyQ="
  [mod."github.com/go-redis/redis/v7"]
    version = "v7.4.1"
    hash = "sha256-VI0cQedFW7abX5XgIHHLn13KvSxAvMQhcD14/4zYpMc="
  [mod."github.com/go-resty/resty/v2"]
    version = "v2.16.0"
    hash = "sha256-IoXwZwYZ19tQQ8JJdd2C3+yz/H2plmydCAUpjUN/7m4="
  [mod."github.com/golang/snappy"]
    version = "v0.0.4"
    hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="
  [mod."github.com/google/go-github"]
    version = "v17.0.0+incompatible"
    hash = "sha256-5EGZnkefwLCEODLICIgaq39UoOzBJqpeLraoc2hJfM8="
  [mod."github.com/google/go-querystring"]
    version = "v1.1.0"
    hash = "sha256-itsKgKghuX26czU79cK6C2n+lc27jm5Dw1XbIRgwZJY="
  [mod."github.com/gorilla/mux"]
    version = "v1.8.1"
    hash = "sha256-nDABvAhlYgxUW2N/brrep7NkQXoSGcHhA+XI4+tK0F0="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.3"
    hash = "sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0="
  [mod."github.com/hashicorp/go-version"]
    version = "v1.7.0"
    hash = "sha256-Umc/Q2mxRrPF4aEcDuDJq4lFBT+PSsnyANfyFwUIaxI="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.11"
    hash = "sha256-LFSIWy0C4VbiuPve0eKHr7Q7s4XtaGzsZ3qpO+6bEgc="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.16"
    hash = "sha256-NC+ntvwIpqDNmXb7aixcg09il80ygq6JAnW0Gb5b/DQ="
  [mod."github.com/mattn/go-tty"]
    version = "v0.0.7"
    hash = "sha256-5hufAOpijxHNw4Nd5fOuAqao7BWbTFinUlim1DN/zSY="
  [mod."github.com/montanaflynn/stats"]
    version = "v0.7.1"
    hash = "sha256-0QXUA/syOtDSBooh3isAffrVAjpSoBmSMMuZfO5maHg="
  [mod."github.com/otiai10/copy"]
    version = "v1.14.0"
    hash = "sha256-xsaL1ddkPS544y0Jv7u/INUALBYmYq29ddWvysLXk4A="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pkg/term"]
    version = "v1.2.0-beta.2"
    hash = "sha256-xb3tIQQk/0890fd9Q+1rtPE9+LoawUQS+m0v+iiB1Lk="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/tcnksm/go-latest"]
    version = "v0.0.0-20170313132115-e3007ae9052e"
    hash = "sha256-pWvNEcL0PKbwsXJSH+BeeRnTrcXpyS0SeJZsjpE55Ag="
  [mod."github.com/xdg-go/pbkdf2"]
    version = "v1.0.0"
    hash = "sha256-UKK8JrdxEeToqs53sUUMUZNQv8w+lzuhd7bNXryMN9o="
  [mod."github.com/xdg-go/scram"]
    version = "v1.1.2"
    hash = "sha256-BPlloFojiFA8TiYIaBPW9BFBNkCmYD68JrY5gry1f64="
  [mod."github.com/xdg-go/stringprep"]
    version = "v1.0.4"
    hash = "sha256-zGNSty2K8PoqMw71AHPvICuUvIzXzUvCW+fCNr3XmLE="
  [mod."github.com/youmark/pkcs8"]
    version = "v0.0.0-20240726163527-a2c0da244d78"
    hash = "sha256-7ETUt8onE9mdUlvHT5xxzfh8mK0qw15ZSYXQCtah9p4="
  [mod."go.mongodb.org/mongo-driver"]
    version = "v1.17.1"
    hash = "sha256-/0TG8G5SHfaRPnCH9L2Nc73JnhZZhb64TJ1pz1x2sHk="
  [mod."golang.org/x/crypto"]
    version = "v0.29.0"
    hash = "sha256-sqckobR2VWucCgb7xpY2wLktnAA+XyXJbhCm80yCo78="
  [mod."golang.org/x/net"]
    version = "v0.31.0"
    hash = "sha256-G+vGyCnn8jywmX3KvsIwhZkOv3+oAERNNeCeiQqfIL0="
  [mod."golang.org/x/sync"]
    version = "v0.9.0"
    hash = "sha256-sGvzGqaaXE5dxohKkpbJMnu+bMmismsSqr8YMtrK+Rc="
  [mod."golang.org/x/sys"]
    version = "v0.27.0"
    hash = "sha256-BXQcF9RrJ55Pq7Nl67TeFGkgkyuKkQ8hHKN4/L4ggWc="
  [mod."golang.org/x/text"]
    version = "v0.20.0"
    hash = "sha256-YP8zSo2e9okqhxVB8me8sJyij2O0tTQEg5t+8bsIUx8="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
