name: Build and Release

on: [push]

env:
  go-version: 1.22.x

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ env.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: '${{ env.go-version }}'
      - name: Install dependencies
        run: go get .
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm, arm64]
        eclude:
        - os: windows
          arch: arm
        - os: darwin
          arch: arm
        - os: darwin
          arch: arm64
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ env.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: '${{ env.go-version }}'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ./bin/screeps-launcher_${{ matrix.os }}_${{ matrix.arch }} ./cmd/screeps-launcher
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: screeps-launcher
          path: ./bin/
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: screeps-launcher
          path: ./bin
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*
      - name: Upload binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin
          asset_name: screeps-launcher_${{ matrix.os }}_${{ matrix.arch }}
          asset_content_type: application/octet-stream